// We are re-exporting the default nitro handler, this allows us to have
// a custom entry point and to be able to still use the default nitro handler
// and have all the routes automatically generated for us.
//
// All the API routes are automatically generated by the file-based routing
// in the `server/api` directory.
export { default } from '#internal/nitro/entries/cloudflare-module';

// We can also export our own handlers, for example for cron jobs, durable objects, etc.
//
// For more information, see https://nitro.unjs.io/deploy/providers/cloudflare
// and https://developers.cloudflare.com/workers/runtime-apis/handlers/
import { getLogger } from './container/resolvers';

// Placeholder for Durable Objects
// For more information, see https://developers.cloudflare.com/durable-objects/
export class MyDurableObject {
  state: DurableObjectState;

  constructor(state: DurableObjectState) {
    this.state = state;
  }

  async fetch(request: Request) {
    const url = new URL(request.url);

    if (url.pathname === '/increment') {
      const value = (await this.state.storage.get('value')) || 0;
      await this.state.storage.put('value', (value as number) + 1);
    }

    return new Response(JSON.stringify(await this.state.storage.list()));
  }
}

// Scheduled handler for Cron Triggers
// For more information, see https://developers.cloudflare.com/workers/runtime-apis/scheduled-event/
export const scheduled: ExportedHandlerScheduledHandler<Env> = async (
  controller,
  env,
  ctx,
) => {
  const logger = getLogger({
    req: {
      header: () => undefined,
      json: async () => ({}),
      addValidatedData: () => {},
      param: () => ({}),
      query: () => ({}),
      valid: () => ({}),
    },
    env,
    ctx,
  } as any);

  try {
    logger.info(
      `Cron job '${controller.cron}' triggered at ${new Date(
        controller.scheduledTime,
      ).toISOString()}`,
    );
    // Add your cron job logic here
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.error(`Error in scheduled handler: ${message}`);
  }
};
