deploy_staging:
  stage: deploy
  image: node:24.11.0-alpine
  script:
    - npm install -g pnpm@latest
    - pnpm install
    - pnpm build
    - node scripts/flatten-wrangler.js staging
    - npx wrangler deploy
  variables:
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
